use_frameworks!

target 'RxFacebook_Example' do
  pod 'RxFacebook', :path => '../'

  target 'RxFacebook_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
