use_frameworks!

target 'RxFacebook_Example' do
  pod 'RxFacebook', :path => '../'

  target 'RxFacebook_Tests' do
    inherit! :search_paths
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.1'
        end
    end
end
